- package.json
- yarn.lock
Included in #13 but will be needed.
> Add bs-custom-file-input dependency

- Gemfile
- Gemfile.lock
- app/javascript/components/HelloWorld.js
- app/javascript/components/Viewer.js
- app/javascript/packs/application.js
- app/javascript/packs/server_rendering.js
- app/views/home/show.html.erb
- app/views/static/show.html.erb
- package.json
- yarn.lock
Might be good to discuss the approach here, but essentially this adds the react-rails package (https://github.com/reactjs/react-rails) which in my opinion is the lesser of the dark magic rails/react integrations.
```erb
<%= react_component("HelloWorld", { greeting: "Hello from Ruby -> JavaScript." }) %>
```
If we need to do this.. I think this is usually the simplest approach.
> React rails proof of concept

- db/schema.rb
Do we need to do this "the right way" instead because of CD?
> Commit schema change that wasnt committed

- app/assets/stylesheets/icons.css
- app/controllers/projects_controller.rb
- app/javascript/components/EditInPlace.js
- app/models/ability.rb
- app/views/layouts/_cols.html.erb
- app/views/layouts/project.html.erb
- app/views/projects/_project.html.erb
- app/views/projects/_workspace_preview.html.erb
- app/views/projects/show.html.erb
- app/views/workspaces/_card.html.erb
- app/views/workspaces/_workspace.html.erb
- app/views/workspaces/index.html.erb
- app/views/workspaces/show.html.erb
- db/migrate/20210405234411_add_fields_to_project.rb
- db/schema.rb
> Add more project fields

- app/assets/stylesheets/application.scss
- app/views/layouts/application.html.erb
- app/views/projects/_project.html.erb
- app/views/projects/index.html.erb
> Make the page background off-white

- app/views/layouts/embedded.html.erb
> Always reload when visiting /embed route

- app/assets/stylesheets/icons.css
- app/controllers/workspaces_controller.rb
- app/views/workspaces/_card.html.erb
- config/routes.rb
> Hook up a way to delete workspaces

- app/assets/stylesheets/icons.css
- app/controllers/workspaces_controller.rb
- app/javascript/components/Favorite.js
- app/views/workspaces/_card.html.erb
- app/views/workspaces/_workspace.json.jbuilder
- db/migrate/20210406184254_add_favorite_to_workspaces.rb
- db/schema.rb
> Add favorite-able workspaces

- app/controllers/workspaces_controller.rb
- app/views/workspaces/_card.html.erb
- config/routes.rb
> Add duplicate workspace action

- app/models/workspace.rb
- app/views/projects/show.html.erb
> Add favorite workspaces list to project page

- app/javascript/components/ShareModal.js
- app/views/workspaces/show.html.erb
- package.json
- yarn.lock
> Share widget

- app/assets/stylesheets/sidebar.scss
- app/views/layouts/_sidebar.html.erb
- app/views/layouts/application.html.erb
> Update styling of sidebar content

- .gitignore
- Gemfile
- Gemfile.lock
- app/assets/stylesheets/resources.scss
- app/controllers/workspaces_controller.rb
- app/jobs/screenshot_workspace_job.rb
- app/models/ability.rb
- app/models/workspace.rb
- app/views/workspaces/_card.html.erb
- app/views/workspaces/show.html.erb
- config/deploy.rb
- config/initializers/config.rb
- config/settings.yml
- config/settings/test.yml
> Screenshot working

- app/assets/stylesheets/sidebar.scss
- app/views/layouts/_sidebar.html.erb
> add an active style for projects

- app/assets/stylesheets/sidebar.scss
- app/views/layouts/_sidebar.html.erb
- app/views/layouts/_top_level_nav.html.erb
- app/views/layouts/project.html.erb
- app/views/projects/index.html.erb
- app/views/projects/show.html.erb
- app/views/workspaces/index.html.erb
> Nav tweaks

- app/assets/stylesheets/resources.scss
- app/javascript/components/EditInPlace.js
- app/views/layouts/_sidebar.html.erb
- app/views/layouts/project.html.erb
- app/views/projects/show.html.erb
🤷‍♂️ 
https://user-images.githubusercontent.com/111218/114557936-07942280-9c1f-11eb-942f-0377c8bdc3a5.mp4
> After performing an edit in place, update other the project titles on the page 

- app/controllers/home_controller.rb
- app/views/home/dashboard.html.erb
- config/routes.rb
> Extract home#dashboard

- .rubocop.yml
- Gemfile
- Gemfile.lock
- app/controllers/projects_controller.rb
- app/controllers/roles_controller.rb
- app/javascript/components/CollaborationModal.js
- app/models/ability.rb
- app/models/project.rb
- app/models/user.rb
- app/views/projects/show.html.erb
- app/views/roles/_user.json.jbuilder
- app/views/roles/index.json.jbuilder
- config/initializers/action_mailer.rb
- config/initializers/devise.rb
- config/locales/devise_invitable.en.yml
- config/routes.rb
- config/settings.yml
- db/migrate/20210422205257_devise_invitable_add_to_users.rb
- db/schema.rb
- spec/controllers/workspaces_controller_spec.rb
- spec/factories/projects.rb
- spec/models/ability_spec.rb
> Add user collaboration modal UI

- app/models/user.rb
As per https://github.com/heartcombo/devise#activejob-integration
Fixes https://github.com/sul-dlss/mise/issues/132  (or at least stops it from showing for the user...)
> Make devise use deliver_later to send mail

- app/controllers/workspaces_controller.rb
- app/models/workspace.rb
- spec/models/workspace_spec.rb
> Prefixes the workspace title with 'Duplicate of'

- app/models/ability.rb
> Add `duplicate` ability as an alias for read actions

- app/controllers/workspaces_controller.rb
> Guard against no current user for workspaces#index

- app/assets/stylesheets/application.scss
- app/views/layouts/_navbar.html.erb
> Add new links for logged out users

- app/controllers/annotations_controller.rb
- app/controllers/application_controller.rb
- app/controllers/concerns/token_ability.rb
- app/controllers/workspaces_controller.rb
- app/jobs/screenshot_workspace_job.rb
- app/models/ability.rb
- spec/factories/annotations.rb
- spec/models/ability_spec.rb
> Use tokens to authorize workspace screenshots

- .eslintrc
- app/javascript/channels/consumer.js
- app/javascript/components/Viewer.js
- app/javascript/controllers/index.js
- app/javascript/controllers/save_workspace_controller.js
- app/javascript/direct_uploads.js
- app/javascript/packs/application.js
- app/views/workspaces/viewer.html.erb
- babel.config.js
- package.json
- yarn.lock
Fixes #144
Also includes:
* Reduce number of eslint violations (down to ~35)
> Prompt user if navigating away from workspace with unsaved changes

- .rubocop.yml
- app/views/workspaces/_card.html.erb
- spec/features/home_page_spec.rb
> acts_as_favoritor doesn't handle missing users well; fixes #168

- app/views/layouts/_sidebar.html.erb
The links in the sidebar don't make sense for anonymous users (who can see projects + worksapces), so don't show it to them 🤷
> Hide the sidebar from anonymous users

- .github/workflows/ruby.yml
Otherwise it complains about using the wrong env when running tests
> Run the setup task with RAILS_ENV test

- .browserslistrc
- Gemfile
- Gemfile.lock
- bin/webpacker
- bin/webpacker-dev-server
- bin/yarn
- config/webpack/webpack.config.js
- config/webpacker.yml
- package.json
- yarn.lock
> Upgrade from webpacker to shakapacker

- Gemfile
- Gemfile.lock
> Update sidekiq gems

- Gemfile.lock
Should fix https://sul-ci-prod.stanford.edu/blue/organizations/jenkins/SUL-DLSS%2Fmise/detail/main/308/pipeline
> Add platform x86_64-linux

- Gemfile
- Gemfile.lock
The mejackreed repo just redirects to PenguinParadigm/annotot
> Switch to PenguinParadigm/annotot
